# -*- coding: utf-8 -*-
"""day1.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wrm_6oupehAAr6yI7mSRpbnNRZo30Tkp
"""

import pandas as pd

df=pd.read_csv('/content/titanic uncleaned.csv')

df

df.head()

df.tail()

df.head(10)

df.info()

df.dtypes

df.shape

df.describe()

df.isnull()

df.isnull().sum()

df['Age_mean_imputed']=df['Age'].fillna(df['Age'].mean())

df['Age_median_imputed']=df['Age'].fillna(df['Age'].median())

df

df

df['Cabin_mode_imputed']=df['Cabin'].fillna(df['Cabin'].mode()[0])

df[['Age_mean_imputed','Age_median_imputed','Cabin_mode_imputed']]

import seaborn as sns
import matplotlib.pyplot as plt

sns.set(style='whitegrid')

plt.figure(figsize=(10,6))
sns.boxplot(data=df,x='Pclass',y='Survived',palette='pastel')





plt.title('boxplot of Survived by Passenger Class',fontsize=16)
plt.xlabel('Passenger Class',fontsize=14)
plt.ylabel('Survived',fontsize=12)

plt.figure(figsize=(10,6))
sns.barplot(data=df,x='Pclass',y='Survived',palette='pastel')

plt.title('barplot of Survived by Passenger Class',fontsize=16)
plt.xlabel('Passenger Class',fontsize=14)
plt.ylabel('Survived',fontsize=12)

from sklearn.preprocessing import LabelEncoder

encoded_data=df.copy()

label_encoder=LabelEncoder()
encoded_data['Sex_Label']=label_encoder.fit_transform(encoded_data['Sex'])

one_hot_encoded = pd.get_dummies(encoded_data['Embarked'], prefix='Embarked')
encoded_data = pd.concat([encoded_data, one_hot_encoded], axis=1)

